############# data collection shortcuts (smartphone login) #######
#
alias rhz='rostopic hz /bair_car/zed/left/image_rect_color'
alias rls='ls -al /media/ubuntu/rosbags'
alias rrm='rm catkin_ws/src/bair_car/rosbags/*'
alias rlog='rm -r ~/.ros/log/*'
alias rla='roslaunch bair_car bair_car.launch use_zed:=true record:=true'
alias rlac='roslaunch bair_car bair_car.launch use_zed:=true record:=true caffe:=true'
alias rgy='rostopic echo /bair_car/gyro'
alias rgp='rostopic echo /bair_car/gps'
alias rac='rostopic echo /bair_car/acc'
alias rst='rostopic echo /bair_car/steer'
alias rmo='rostopic echo /bair_car/motor'
alias ren='rostopic echo /bair_car/encoder'
alias rcd='cd /media/ubuntu/rosbags'
alias ssd='sudo shutdown -h now'
alias rcn='echo $COMPUTER_NAME'
alias riv='rosrun image_view image_view image:=/bair_car/zed/right/image_rect_color'

######################## for .bashrc from MacBook #################
#
#echo "source ~/8August2016_common_aliases"
#export DISPLAY=:0.0
alias gacp="git add -u;git commit -m 'gacp';git push origin master"
alias gckzpy3="git clone https://github.com/karlzipser/kzpy3.0.git"
alias ipy="ipython --no-banner"
export PYTHONPATH=~:$PYTHONPATH
#export PYTHONPATH=~/kzpy3/caf/layers:$PYTHONPATH
#export PYTHONPATH=~/kzpy3/caf2/layers:$PYTHONPATH
export PYTHONSTARTUP=~/kzpy3/vis.py
export PATH=~/kzpy3/scripts:$PATH