#!/bin/bash
#system('rsync -rav ~/Desktop/Data/subjects/ ~/Google\ Drive/Data_Google_Drive/subjects');
#system('rsync -rav ~/Desktop/Data/fmri_scanning_experiments/ ~/Google\ Drive/Data_Google_Drive/fmri_scanning_experiments');
echo 'rsync script.'
#g#!HV3419
rsync -P -rav --exclude 'Icon*' --exclude 'analysis' --exclude 'experiments' --exclude 'freesurfer' --exclude 'osx' --exclude 'stimuli' --exclude '_blank_scan' --exclude 'AK' --exclude 'AV' --exclude 'CW' --exclude 'DR' --exclude 'KW' --exclude 'KZ' --exclude 'Phantom' --exclude 'SK' --exclude 'TN' --exclude 'dcm' --exclude 'edf' --exclude 'fsl' --exclude 'info' --exclude 'log' --exclude 'mat' --exclude '*.feat' --exclude 'earlier' --exclude 'design*' --exclude '*.fsf' --exclude '*.gfeat' --exclude 'runs' --exclude '_*' --exclude 'subjects/HVO/2015/1' ~/Data/ droponly@stone.psychology.wustl.edu:"/stone/ext3/knk/karlzipser/Data" #~/Desktop/karlzipser/Data


#rsync -P -rav --exclude 'Icon*' --exclude 'analysis' --exclude 'experiments' --exclude 'freesurfer' --exclude 'osx' --exclude 'stimuli' --exclude '_blank_scan' --exclude 'AK' --exclude 'AV' --exclude 'CW' --exclude 'DR' --exclude 'KW' --exclude 'KZ' --exclude 'Phantom' --exclude 'SK' --exclude 'TN' --exclude 'dcm' --exclude 'edf' --exclude 'fsl' --exclude 'info' --exclude 'log' --exclude 'mat' --exclude '*.feat' --exclude 'earlier' --exclude 'design*' --exclude '*.fsf' --exclude '*.gfeat' --exclude 'runs' --exclude '_*' --exclude 'subjects/HVO/2015/1' --exclude 'nii' ~/Data/ ~/Desktop/karlzipser/Data

#rsync -P -rav --exclude 'Icon*' --exclude 'analysis' --exclude 'experiments' --exclude 'freesurfer' --exclude 'osx' --exclude 'stimuli' --exclude '_blank_scan' --exclude 'AK' --exclude 'AV' --exclude 'CW' --exclude 'DR' --exclude 'KW' --exclude 'KZ' --exclude 'Phantom' --exclude 'SK' --exclude 'TN' --exclude 'dcm' --exclude 'edf' --exclude 'info' --exclude 'log' --exclude '*.z_scored_filtered_func_data.mat' --exclude 'mat' --exclude 'earlier' --exclude '*.gfeat' --exclude 'runs' --exclude '_*' --exclude 'subjects/HVO/2015/1' --exclude 'nii' ~/Data/ karlz@neuro-calhpc.berkeley.edu:/clusterfs/cortex/scratch/karlz/Data